import type { Metadata } from "next";
import { Geist, Geist_Mono,Montserrat } from "next/font/google";
import "./globals.css";



const montserratSans = Montserrat({
  variable:"--font-montserrat",
  subsets:["latin"],
  display:"swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
